### ISSUE TITLE
example usage with webpack config

### ISSUE THREAD

**Issue by softmarshmallow** [modosc/global-jsdom#102]
such like 

```
		fallback: {
			fs: false,
			child_process: false,
            net: false,
            tls: false,
			stream: false,
			assert: false,
			url: false,
			buffer: false,
			querystring: false,
			zlib: false,
			os: false,
			crypto: require.resolve("crypto-browserify")
        },
		mainFields: ['module', 'main'],
```

**Comment by modosc** [comment]
can you give me an example of when/why you'd use this with webpack?

**Comment by softmarshmallow** [comment]
I'm trying to make 
jupyter vscode extension to work on the browser, which nbnote previewer requires, jsdom. which does not compiles via webpack. and searching for jsdom browserfy let me here.

https://github.com/bridgedxyz/github.surf/tree/main/extensions/jupyter-web
trying to make this work. https://github.surf/deepmind/deepmind-research/blob/HEAD/memo/load_memo_data.ipynb

**Comment by modosc** [comment]
so [jsdom-global](https://github.com/rstacruz/jsdom-global) worked in a browser by exporting an [empty function](https://github.com/rstacruz/jsdom-global/blob/master/browser.js) from the [browser field of package.json](https://github.com/rstacruz/jsdom-global/blob/master/package.json#L6). iirc the ordering of how webpack decides which of these to use was why i removed that support (see [here](https://github.com/webpack/webpack/issues/4674) and [here](https://webpack.js.org/guides/package-exports/#providing-different-versions-depending-on-target-environment). for now i don't want to add this functionality and i'd recommend using `jsdom-global` instead. if enough people wanted this to work i could add such a shim but pretending to provide a dom via `jsdom` when it's not necessary in a browser is a pretty small edge case imho.
