### ISSUE TITLE
jsdom < 16 required - unmet peer dependency warning

### ISSUE THREAD

**Issue by mohanraj-r** [modosc/global-jsdom#12]
Current version of jsdom is 16.2.2
But global-jsdom depends on jsdom < 16
This results in unmet peer dependency warning when installing packages
Wondering if the jsdom < 16 requirement is still valid or could be relaxed ?

**Comment by modosc** [comment]
thanks, that was wrong. fixed in https://github.com/modosc/global-jsdom/commit/a15d359738b90083a96b2a4e008f002760fc09e8

i'm going to roll a new release later today.

**Comment by mohanraj-r** [comment]
Thanks for the prompt response @modosc
