### ISSUE TITLE
semver for jsdom in peerDependencies

### ISSUE THREAD

**Issue by alumni** [modosc/global-jsdom#245]
Currently any jsdom version is accepted because the semver contains the "or" operator (`>=10.0.0 || <20` matches everything including 9, 20, 21). To achieve the same result, `*` could be used instead.

If you want to match everything between 10 and 20 (open interval), the semver should be: `>=10 <=20`.

**Comment by modosc** [comment]
thanks for the report, this will go out in the next release

**Comment by alumni** [comment]
Cool! Might want to allow the latest jsdom version though: `<=20` or `<21` instead of `<20`.

Yarn (and others) is more strict than npm with version compatibility and would complain.

**Comment by modosc** [comment]
oops, fixed in https://github.com/modosc/global-jsdom/commit/b2574fc6e35461f9084f4e5213ced0f82cbc3114
