### ISSUE TITLE
Load HTML and run embedded scripts

### ISSUE THREAD

**Issue by jpilgrim** [modosc/global-jsdom#316]
Is it possible to load an HTML file and run embedded scripts?

In JSDOM, this is possible as follows:
```
const dom = await JSDOM.fromFile("myhtml.html", 
                          { runScripts: "dangerously", resources: "usable" });
// await scripts to be run
await new Promise(resolve => dom.window.addEventListener("load", resolve) );
const document = dom.window.document;
// check modified DOM:
expect(document.getElementById("generatedByScript").toBeTruthy();  
...
```

Unfortunately, this is not working with global-jsdom. E.g.,

```
globalJsdom(readFileSync("myhtml.html", { encoding: "utf-8" }),
                          { runScripts: "dangerously", resources: "usable" });
// await scripts to be run
await new Promise(resolve => dom.window.addEventListener("load", resolve) );
// check modified DOM:
expect(document.getElementById("generatedByScript").toBeTruthy();  
...
```

is not working. The document is loaded, but the script has not been executed. The event has been fired, that is, the promise is resolve, though.

**Comment by modosc** [comment]
one thing i noticed is this line:
```
await new Promise(resolve => dom.window.addEventListener("load", resolve) );
```
i don't believe `dom` is defined anywhere by `global-jsdom` - you could try `$jsdom.window` or just `window` (both of which are put into the global namespace [here](https://github.com/modosc/global-jsdom/blob/main/packages/global-jsdom/esm/index.mjs#L45-L51). 

another thing to consider is that your implementation is missing the call to [normalizeFromFileOptions](https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/lib/api.js)  (see [here](https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/lib/api.js#L149C15-L149C39)) - i'm unsure if that would make a difference or not.

**Comment by modosc** [comment]
closing out - please repoen if you can narrow this issue down.
