### ISSUE TITLE
Add type information for `global.$jsdom`

### ISSUE THREAD

**Issue by DanKaplanSES** [modosc/global-jsdom#331]
When I used `global.$jsdom` in typescript, it had a type of `any`. Can you give it a type in the index.d.ts file? 

Thanks

**Comment by modosc** [comment]
i don't use ts so i won't be able to do this. i'm happy to accept a pr for this though, thanks!

**Comment by DanKaplanSES** [comment]
I have created a PR and manually tested it on another local typescript project.
