### ISSUE TITLE
jsdom 23 unsupported

### ISSUE THREAD

**Issue by smhg** [modosc/global-jsdom#365]
Is there any reason why jsdom >22 is [not supported](https://github.com/modosc/global-jsdom/blob/9e9e85b07c2a8135496ad7bf5614f22ddd2f63cc/package.json#L33)? I'm happy to create a PR to fix this.

**Comment by modosc** [comment]
> Is there any reason why jsdom >22 is [not supported](https://github.com/modosc/global-jsdom/blob/9e9e85b07c2a8135496ad7bf5614f22ddd2f63cc/package.json#L33)? I'm happy to create a PR to fix this.

no specific reason. a while back a jsdom release caused some breakage which is why i've been manually ratcheting this up.

pr would be welcome here.

**Comment by modosc** [comment]
fixed in https://github.com/modosc/global-jsdom/pull/366, will release a new version later today

**Comment by smhg** [comment]
@modosc thank you!
