### ISSUE TITLE
jsdom 22 not supported in v9.2.x?

### ISSUE THREAD

**Issue by attekemppila** [modosc/global-jsdom#376]
v9.2.0 changed supported jsdom range from `">=22 <23"` -> `">=23 <24"`.

https://github.com/modosc/global-jsdom/pull/366/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L33-R33

(btw. You forgot to update README.md, it still says "jsdom >= 22 or above"  ([link](https://github.com/modosc/global-jsdom/blob/ff3138e508f238e920932419f03baa4807d90205/README.md?plain=1#L9)))

It would have been nicer if v9.2.0 had just updated the end-of-range, not the start-of-range (that is, `">= 22 <24"`. Can we get an update?). Or v9.2.0 should have been a major update (-> v10), since it changes supported jsdom range in a breaking way (you must update jsdom version also).

I use [Renovate](https://docs.renovatebot.com/) to auto-update my dependencies. My renovate config is fairly default. Basically it can't handle minor-update in global-jsdom and major-update in jsdom versions. If both were major-updates, it would have been ok. Or if the global-jsdom's jsdom range were laxer (`">= 22 <24"`), it would have been ok.

Okey, this is not a major problem. I can fix my dependencies by hand. But still, something to consider in the future. Thank you.

**Comment by modosc** [comment]
i think i'm going to change the versioning scheme to be pinned to the major version of `jsdom`, eg for [jsdom 24] (https://github.com/modosc/global-jsdom/pull/380) i'll release v24.0.0 with the range `>= 24, <25`. this will make major-version `jsdom` bumps into major version `global-jsdom` bumps and will allow me to remove that line in the `README.md`.

**Comment by modosc** [comment]
i released `v24.0.0` and moved to the new versioning scheme.
