### ISSUE TITLE
Support for jsDOM 25.0.0

### ISSUE THREAD

**Issue by joergplewe** [modosc/global-jsdom#421]
Hi all!

Seems that global-jsdom won't allow for jsDOM >24

```
"peerDependencies": {
    "jsdom": ">=24 <25"
  },
```

Can this be extended?

**Comment by modosc** [comment]
done in #422

**Comment by goosewobbler** [comment]
@modosc That just updated the devDep, this issue is about the peerDep range: https://github.com/modosc/global-jsdom/pull/422/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R33

**Comment by modosc** [comment]
> @modosc That PR just updated the devDep, this issue is about the peerDep range: https://github.com/modosc/global-jsdom/pull/422/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R33

oops, meant https://github.com/modosc/global-jsdom/pull/426
